apiVersion: v1
kind: Pod
metadata:
  name: recipient
  labels:
    component: recipient
spec:
  containers:
  - name: recipient
    image: REPO/recipient
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recipient
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    component: recipient
